### PR TITLE
Fix Supernatural Stamina

### LINKED ISSUE #1416: crash when playing Supernatural Stamina
Play Supernatural Stamina targeting your own creature results in a crash:
```
Exception from controller.runGame: java.lang.NullPointerException
magic.exception.GameException: java.lang.NullPointerException
        at magic.model.MagicGame.doAction(MagicGame.java:565)
        at magic.model.phase.MagicPhase.executePhase(MagicPhase.java:43)
        at magic.model.MagicGame.executePhase(MagicGame.java:476)
        at magic.ui.screen.duel.game.SwingGameController.executeNextEventOrPhase(SwingGameController.java:758)
        at magic.ui.screen.duel.game.SwingGameController.runGame(SwingGameController.java:720)
        at magic.ui.screen.duel.game.DuelGameScreen$1.run(DuelGameScreen.java:51)
Caused by: java.lang.NullPointerException
        at magic.model.ARG.wordrun(ARG.java:101)
        at magic.model.MagicAbility$152.addAbilityImpl(MagicAbility.java:1268)
        at magic.model.MagicAbility.addAbility(MagicAbility.java:1824)
        at magic.model.MagicAbility.getAbilityList(MagicAbility.java:1881)
        at magic.model.action.GainAbilityAction.<init>(GainAbilityAction.java:29)
        at magic.model.action.GainAbilityAction.<init>(GainAbilityAction.java:49)
        at Supernatural_Stamina$1$_executeEvent_closure1.doCall(Supernatural_Stamina.groovy:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
        at com.sun.proxy.$Proxy11.doAction(Unknown Source)
        at magic.model.event.MagicEvent.processTargetPermanent(MagicEvent.java:621)
        at Supernatural_Stamina$1.executeEvent(Supernatural_Stamina.groovy:17)
        at magic.model.event.MagicEvent.executeEvent(MagicEvent.java:726)
        at magic.model.MagicGame.executeEvent(MagicGame.java:796)
        at magic.model.stack.MagicItemOnStack.resolve(MagicItemOnStack.java:130)
        at magic.model.stack.MagicCardOnStack.resolve(MagicCardOnStack.java:113)
        at magic.model.action.StackResolveAction.doAction(StackResolveAction.java:13)
        at magic.model.MagicGame.doAction(MagicGame.java:563)
        ... 5 more
```

### PR DESCRIPTION
**Pull request by Fulmene**
Fixes #1416

### CODE REVIEW

File: release/Magarena/scripts/Supernatural_Stamina.groovy [hunk 1]
```diff
@@ -1,4 +1,24 @@
...
+            permanent,
+            permanent.getOwner(),
+            permanent.getCard(),
+            this,
+            "Return SN to the battlefield tapped under PN's control."
+        );
+    }
+    @Override
+    public void executeEvent(final MagicGame game, final MagicEvent event) {
+        final MagicPermanent source = (MagicPermanent)event.getSource();
```
Comment (melvinzhang) [inline release/Magarena/scripts/Supernatural_Stamina.groovy]: source is not used, should be removed.

File: release/Magarena/scripts/Supernatural_Stamina.groovy [hunk 2]
```diff
@@ -9,14 +29,14 @@ def Return = MagicAbility.getAbility("When SN dies, return it to the battlefield
                 POS_TARGET_CREATURE,
                 this,
                 "Until end of turn, target creature\$ gets +2/+0 " +
-                "and gains \"When this creature dies, return it to the battlefield tapped under its owner's control.\""
```
Comment (melvinzhang) [inline release/Magarena/scripts/Supernatural_Stamina.groovy]: `this creature` is the correct phrasing as it is in the oracle text. Please restore the word `this`.
