### PR TITLE
Fix abilities that reveal cards from top of library until certain condition

### LINKED ISSUE #1527: Crash when casting card with Treasure Keeper and it also casts the wrong card
[Crashed when casting Syndicate Trafficker](https://circleci.com/gh/Fulmene/magarena/510)

[Cast a Colossal Dreadmaw](https://circleci.com/gh/Fulmene/magarena/511) (a 6 CMC card)

["Cast" a Sunpetal Grove](https://circleci.com/gh/Fulmene/magarena/509) (a land card)

### PR DESCRIPTION
**Pull request by Fulmene**
- Tezzeret, Master of Metal
- Ajani, Valiant Protector
- Madcap Experiment
- Treasure Keeper

I had some problem with "cards not cast this way" in Treasure Keeper, since it included the CMC 3 or less nonland card that isn't cast because the player chose not to cast it. Then I remembered Cascade exists.

Fixes #1527

### CODE REVIEW

File: release/Magarena/scripts/Ajani__Valiant_Protector.groovy [hunk 1]
```diff
@@ -6,23 +6,29 @@
...
             def predicate = { final MagicCard card -> card.hasType(MagicType.Creature) };
-            final MagicCardList nonTarget = new MagicCardList(library.takeWhile({ !predicate(it) }));
-            if (library.any(predicate)) {
-                final MagicCard target = library.find(predicate);
-                game.doAction(new RevealAction(nonTarget.plus(target)));
-                game.doAction(new ShiftCardAction(target, MagicLocationType.OwnersLibrary, MagicLocationType.OwnersHand));
-            } else {
-                game.doAction(new RevealAction(nonTarget));
+            final MagicCardList revealed = new MagicCardList();
+            MagicCard target = MagicCard.NONE;
```
Comment (melvinzhang) [inline release/Magarena/scripts/Ajani__Valiant_Protector.groovy]: mutable variable target is not necessary, use `break` to exit the while loop when top card matching predicate is found.

File: release/Magarena/scripts/Madcap_Experiment.groovy [hunk 2]
```diff
@@ -15,19 +15,25 @@
...
-                game.doAction(new ShiftCardAction(it, MagicLocationType.OwnersLibrary, MagicLocationType.BottomOfOwnersLibrary))
+            final MagicCardList revealed = new MagicCardList();
+            MagicCard target = MagicCard.NONE;
+            int amount = 0;
+            while (target == MagicCard.NONE && library.size() > 0) {
+                final MagicCard topCard = library.getCardAtTop();
+                game.doAction(new RevealAction(topCard));
+                amount++;
+                if (predicate(topCard)) {
+                    target = topCard;
```
Comment (melvinzhang) [inline release/Magarena/scripts/Madcap_Experiment.groovy]: remove target, use `break` to exit the loop

File: release/Magarena/scripts/Tezzeret__Master_of_Metal.groovy [hunk 3]
```diff
@@ -6,23 +6,29 @@
...
-                game.doAction(new ShiftCardAction(target, MagicLocationType.OwnersLibrary, MagicLocationType.OwnersHand));
-            } else {
-                game.doAction(new RevealAction(nonTarget));
+            final MagicCardList revealed = new MagicCardList();
+            MagicCard target = MagicCard.NONE;
+            while (target == MagicCard.NONE && library.size() > 0) {
+                final MagicCard topCard = library.getCardAtTop();
+                game.doAction(new RevealAction(topCard));
+                if (predicate(topCard)) {
+                    target = topCard;
```
Comment (melvinzhang) [inline release/Magarena/scripts/Tezzeret__Master_of_Metal.groovy]: remove target, use `break` to exit the while loop
